version: '3.7'

services:
    db:
        container_name: symfony-film-db
        image: mysql:8.0.17
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    web:
        container_name: symfony-film-web
        build: .docker/php
        depends_on:
            - db
        volumes:
            - .:/var/www/project:cached
        ports:
            - 8010:80
    node:
        container_name: symfony-film-node
        image: node:12-alpine
        command: sh -c "yarn install && yarn encore dev --watch"
        volumes:
            - .:/app:cached
        working_dir: /app

    composer:
        container_name: symfony-film-composer
        image: composer:1.9.0
        command: install
        depends_on:
            - web
        volumes:
            - .:/app
