version: '3.7'

#secrets:
#    my_secret:
#        file: ./my-secret.txt

services:
    db:
        container_name: symfony-film-db
        image: mysql:8.0.17
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
#            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#            - MYSQL_ROOT_PASSWORD=/run/secrets/my_secret
#            - MYSQL_RANDOM_ROOT_PASSWORD=yes
#        secrets:
#            - my_secret
    web:
        container_name: symfony-film-web
        build: .docker/php
        depends_on:
            - db
        volumes:
            - .:/var/www/project:cached
        ports:
            - 8010:80
    node:
        container_name: symfony-film-node
        image: node:12-alpine #node:alpine3.10
        command: sh -c "yarn install && yarn encore dev --watch"
        volumes:
            - .:/app:cached
        working_dir: /app

    composer:
        container_name: symfony-film-composer
        image: composer:1.9.0
        command: install
        depends_on:
            - web
        volumes:
            - .:/app
